import fs from "node:fs";
import path from "node:path";
import type { NextConfig } from "next";

/** 301 map generated by scripts/import-xenforo.ts (absent until an import runs). */
function xenforoRedirects(): Array<{
  source: string;
  destination: string;
  permanent: boolean;
}> {
  try {
    const file = path.join(process.cwd(), "data", "xenforo-redirects.json");
    if (!fs.existsSync(file)) return [];
    const map = JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, string>;
    return Object.entries(map)
      .filter(([source, destination]) => source !== destination)
      .map(([source, destination]) => ({
        source,
        destination,
        permanent: true,
      }));
  } catch {
    return [];
  }
}

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  output: "standalone",
  serverExternalPackages: ["better-sqlite3", "pg", "kysely"],
  images: {
    formats: ["image/avif", "image/webp"],
    remotePatterns: [
      { protocol: "https", hostname: "atrium.com" },
    ],
  },
  async redirects() {
    return [
      { source: "/lore", destination: "/wiki", permanent: false },
      { source: "/lore/", destination: "/wiki", permanent: false },
      { source: "/pages/home", destination: "/", permanent: false },
      { source: "/pages/home/", destination: "/", permanent: false },
      ...xenforoRedirects(),
    ];
  },
};

export default nextConfig;
